### ISSUE TITLE
Access Violation in OnFailure callback

### ISSUE THREAD

**Issue by sebjf** [pixiv/webrtc#12]
Hello. Thank you very much for this project.

If I make a mistake setting up a PeerConnection, the SetSessionDescriptionObserver OnFailure callback throws an access violation. I think this is due to a marshalling issue.

![image](https://user-images.githubusercontent.com/5058369/85124297-96175d80-b221-11ea-8fbb-89c8fef0d987.png)

Above is the exception in native code. The only variable with the same value as the read location (6) is ctype.

Comparing the managed and unmanaged signatures, the managed takes an RTCError struct. Are you relying on the struct having the same layout on the stack as the last arguments in the unamanaged signature?

jesp.h@56   `void (*on_failure)(void*, enum WebrtcRTCErrorType, const char*);`
jesp.cs@187         `private delegate void FailureHandler(IntPtr context, RtcError error);`

If I update the delegate signature and construct the RTCError in DisposableSetSessionDescriptionObserver then Unity recieves the OnFailure call correctly.

jesp.cs@214 
```
        [MonoPInvokeCallback(typeof(FailureHandler))]
        private static void OnFailure(IntPtr context, RtcErrorType type, string message)
        {
            var handle = (GCHandle)context;

            ((IManagedSetSessionDescriptionObserver)handle.Target).OnFailure(
                new RtcError(type, message)
            );
        }
```

Is this the correct fix or was there a reason it was done the other way?

Unity 2019.3.12f1 .NET Standard 2.0.

**Comment by akihikodaki** [comment]
> Is this the correct fix or was there a reason it was done the other way?

Your problem analysis is absolutely right.

However, the fix has one problem; you cannot use `string` as the third argument of `FailureHandler`. Instead, you can use `IntPtr` and unmarshal the pointed buffer with `System.Runtime.InteropServices.Marshal.PtrToStringAnsi`, which do not free the buffer by its own.

If you use `string` as an argument of a delegate, .NET will automatically free the original `char*`. However, the original argument is `const char*` (i.e. not expected to be freed by the callee) in this case. The code actually responsible for freeing the underlying buffer here is in C++, and the use of `string` as an argument in C# will cause double-free. See `Pixiv.Rtc.Interop.MoveToString` for an example correctly unmarshalling `const char*` into `string`.

Please open a pull request if you write a new fix so that I can review it. Thanks.
