### ISSUE TITLE
Alpha channel encoding

### ISSUE THREAD

**Issue by anchalsinha** [pixiv/webrtc#7]
Is it possible to encode an RGBA image and preserve its transparency when decoded? I have made by own variant of the sample Unity application provided and it seems like the alpha channel isn't being encoded.

**Comment by akihikodaki** [comment]
The encoding such as H.264 is unlikely to support alpha channel and therefore this library will not support alpha channel.
However, you may double the video resolution and fill the extra area with the values of the alpha channel so that you can transfer alpha channel as well. It can be more efficient if you encode alpha channel taking YUV color space used by the encoding into consideration.
